### ISSUE TITLE
How to get transparency from mtl file using simple Wavefront OBJ file loader library and apply to the 3d object in opengl es android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [javagl/Obj#10]
Hai iam working ar-core augment reality in android.Rendering object using opengl es and reading obj and mtl file using simple Wavefront OBJ file loader library.I want to know how to get transparency factor from mtl file using this library and apply to the object using opengl es.

**Comment by javagl** [comment]
The opacity is called "dissolve" in MTL (search for "dissolve" on http://paulbourke.net/dataformats/mtl/ ). It may be obtained by calling [`Mtl#getD()`](https://github.com/javagl/Obj/blob/master/src/main/java/de/javagl/obj/Mtl.java#L131)

---

**Note: There may be a minor API change regarding MTL in the next release: The return type of the `Mtl#getD` method will probably be a `Float`!** 

The goal is to indicate whether the `d` property was contained in the MTL file or not. If the MTL file does not contain the `D` property, then the return value will be `null`:

    Float dissolve = mtl.getD();
    if (dissolve == null) { /* No opacity information }
    else { object.setOpacity(dissolve); }

The `Mtl` structure originally contained only a tiny fraction of all the properties that may be contained in an MTL file, and there recently has been a PR to extend the material support (see https://github.com/javagl/Obj/pull/7 ). There is a branch that contains a first version of this extended material support - see e.g. https://github.com/javagl/Obj/blob/materials/src/main/java/de/javagl/obj/Mtl.java#L317 

---

However, actually *applying* this opacity/transparency to a rendered object is tricky. The current renderer of GoogleAR does not really support transparency, as far as I know. In some (simple) cases, transparency may be emulated by using a color where the alpha component is not 1.0. But you'll have to integrate this in a separate rendering pass. One of the issues is that you have to disable the Z-buffer when the transparent objects are rendered. In order to render transparent objects without artifacts, you either have to sort the objects in z-Order (which may not always be possible without ambiguities), or apply sophisticated techniques like https://en.wikipedia.org/wiki/Order-independent_transparency (which might not fully be possible on GL ES). 

(I'm not an OpenGL/rendering expert, though. You might consider opening an issue about transparency support in the GoogleAR repo, but I doubt that it will be easy to support this out-of-the-box...)

**Comment by ArigarasuthanRepo** [comment]
Thank you for the info. is object.setObacity property in java?

**Comment by javagl** [comment]
The `setOpacity` call was pesudocode. A function like this would have to be added to the https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/rendering/ObjectRenderer.java , but until now, it does not support transparency as far as I see. It **might** support it, via the [`BlendMode`](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/rendering/ObjectRenderer.java#L221), but I haven't yet looked into the details.

**Comment by javagl** [comment]
I think that the issue itself is resolved (as it was largely unrelated to this library in the first place...)
