### ISSUE TITLE
Cannot load an MTL with MTL Reader, application crashes with NullPointerException

### ISSUE THREAD

**Issue by nayanpts** [javagl/Obj#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'void de.javagl.DefaultMtl.setKd(float, float, float)' on a null object reference

Tried loading it with input stream as well as with reader instance

**Comment by javagl** [comment]
I've never encountered this particular error message, but a quick websearch indicates that it is just a simple `NullPointerException`, with a detail message that is specific for Android. 

I'll look into this. From a quick glance, I think that this might be caused by a missing `newmtl` line in the MTL file. (If this is the case, I'll review whether this is compliant to the standard, or whether it may be handled more gracefully).

Could you provide the MTL file that causes the error?

**Comment by nayanpts** [comment]
Here is the MTL file: [sample.zip](https://github.com/javagl/Obj/files/1448540/sample.zip)
Thanks for the quick response, I was able to get this work on other desktop OBJ importers

**Comment by javagl** [comment]
The MTL file indeed seems to be broken a bit. A hex editor reveals that there are some (unprintable) characters at the beginning of the file:

![brokenmtl](https://user-images.githubusercontent.com/5597569/32704478-0ea9bf9e-c806-11e7-9780-8643631e33d3.png)

Copying the actual file contents into a new, plain (text) file should resolve the issue. 
```
newmtl DEFAULT_MTL
Kd 0.695 0.743 0.790

newmtl MTL0 
Kd 0.200 0.208 0.188

newmtl MTL1 
Kd 0.647 0.620 0.588

newmtl MTL2 
Kd 0.949 0.757 0.176

newmtl MTL3 
Kd 0.898 0.918 0.929

newmtl MTL4 
Kd 0.847 0.847 0.847

newmtl MTL5 
Kd 0.000 0.000 0.000

newmtl MTL6 
Kd 1.000 1.000 0.000

newmtl MTL7 
Kd 1.000 1.000 1.000
```

**Comment by javagl** [comment]
Assuming that this can be closed, because it seems to be caused only by the corrupt input file.

**Comment by javagl** [comment]
These bytes are actually a https://de.wikipedia.org/wiki/Byte_Order_Mark
