### ISSUE TITLE
 The filename of mtllib written in the obj file is not used

### ISSUE THREAD

**Issue by marron9999** [javagl/Obj#20]
On package de.javagl.jgltf.obj.model;
      public class ObjGltfModelCreator
Method:  public GltfModel create(URI objUri) throws IOException

1) Initial

String mtlFileName = baseName + ".mtl";
URI mtlUri = IO.makeAbsolute(baseUri, mtlFileName);

2) Reading obj file

Obj obj = readObj(objUri);

3) Check exist of mtl file
but, the filename of mtllib written in the .obj file is not used

if (IO.existsUnchecked(mtlUri))

**Comment by javagl** [comment]
You're absolutely right.

<sup>(This issue belongs into [JglTF](https://github.com/javagl/JglTF), but ... that doesn't matter now)</sup>

For some reason, the code made the assumption that the MTL file name and the OBJ file name are the same (only with different extensions). This is fixed with https://github.com/javagl/JglTF/commit/fc8e0eb039345ff26138f4b3feac945b727e25d0 : Now, it uses the file name from the `mtllib` of the OBJ file. 

---


An aside: It is impossible to fix this in a strictly backward-compatible way. A user could have used an OBJ file called `example.obj` that used `mtllib referenced.mtl`, and an `example.mtl` in the same directory. The old behavior was to _ignore_ the `referenced.mtl`, and use the `example.mtl` instead. The new behavior is that it will try to load the data from the `referenced.mtl`. This is the _right_ behavior, though. When no `mtllib` file name is given, it will still try to load the "default" MTL file. But I don't know how common this case actually is. 

Another aside: There could be _multiple_ MTL files for a single OBJ file. This is probably an artiact from the time where file names could not contain _spaces_. As mentioned [in the `ObjReader`](https://github.com/javagl/Obj/blob/59b0c3266fcef8c07f0d33bb7821d4472632e9a2/src/main/java/de/javagl/obj/ObjReader.java#L195), the Obj library currently supports only _one_ MTL file. But this is somewhat tangential to this issue...

---

I added the [`TestMtlFileHandling.java`](https://github.com/javagl/JglTF/blob/fc8e0eb039345ff26138f4b3feac945b727e25d0/jgltf-obj/src/test/java/de/javagl/jgltf/obj/TestMtlFileHandling.java) that I used for locally testing this, together with the required input OBJ- and MTL files.
