### ISSUE TITLE
Is really need the initial value (kd, ks, ka) of DefaultMtl 

### ISSUE THREAD

**Issue by marron9999** [javagl/Obj#21]
Is really need the initial value  (kd, ks, ka) of DefaultMtl ? 
I think it should be possible to determine the case where no value is specified.

Current codes

    DefaultMtl(String name)
    {
        this.name = name;
        ka = new DefaultFloatTuple(0,0,0);
        kd = new DefaultFloatTuple(0,0,0);
        ks = new DefaultFloatTuple(0,0,0);
        ns = 100.0f;
        d = 1.0f;
    }

    private final DefaultFloatTuple ka;
    private final DefaultFloatTuple kd;
    private final DefaultFloatTuple ks;

**Comment by javagl** [comment]
I once considered to extend the MTL support. And there actually already _is_ an `Mtl` interface (in a branch) where this is implemented: https://github.com/javagl/Obj/blob/materials/src/main/java/de/javagl/obj/Mtl.java#L114 

When you scroll through that interface (or think about it) you'll notice that the same could be said for the `d` and `ns` values. They must be `Float` (instead of `float`), so that it is possible to indicate whether the value was present. 

However, the last modification on that branch was four years ago - I _could_ try to allocate some time to wrap it up, and create a new release (which would be `1.x.x`, because this would be a breaking change). But I cannot promise any timeline here.

**Comment by javagl** [comment]
The PR https://github.com/javagl/Obj/pull/25 extended the material support. This is part of version `0.4.0` that has just been released in Maven Central. The README contains a hint about the change (which is a _breaking_ change in terms of the API): The `Mtl::get...` methods will now return `null` for the values that have not been contained in the MTL file.
